version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - ${DB_PORT}:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
        restart: unless-stopped
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        ports:
            - ${DB_GUI_PORT}:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASS}
            - ME_CONFIG_MONGODB_SERVER=${DB_SERVER}
        depends_on:
            - mongodb
        restart: unless-stopped

volumes:
  data: {}

networks:
    default:
        name: mongodb_network